#!/usr/bin/env python3

import subprocess
import re
import sys


def die(msg):
    print(msg)
    sys.exit(1)


def usage():
    die("""
Usage:
  vm list
  vm start <name>
  vm stop <name>
  vm ssh <name>
  vm vnc <name>
""")

# TODO create, delete, clone support


def sh(cmd):
    return subprocess.check_output(cmd, shell=True).decode('utf-8')


def run(cmd):
    subprocess.call(cmd, shell=True)


def main():
    if len(sys.argv) < 2:
        usage()

    cmd = sys.argv[1]
    arg = None
    if len(sys.argv) >= 3:
        arg = sys.argv[2]
        if not re.match("""^[A-Za-z0-9_]+$""", arg):
            die("Bad argument '{}' - should be [A-Za-z90-9_]+".format(arg))

    if cmd == "list":
        # TODO better formatting and sorting
        run("vboxmanage list vms --long | egrep '^(Name|State)'")
    elif arg is not None:
        if cmd == "start":
            run("vboxmanage startvm --type headless {}".format(arg))
        elif cmd == "stop":
            run("vboxmanage controlvm {} poweroff".format(arg))
        elif cmd == "ssh":
            tmp = sh("vboxmanage showvminfo {} | grep ssh-forwarding".format(arg))
            port = re.search("""host port = (\d+)""", tmp).group(1)
            run("ssh -p {} localhost".format(port))
        elif cmd == "vnc":
            tmp = sh(
                "vboxmanage showvminfo {} | grep VRDE | grep TCP/Ports".format(arg))
            port = re.search("""TCP/Ports  = "(\d+)""", tmp).group(1)
            run(('''echo -en '\\x2e\\x2d\\xbf\\x57\\x6e\\xb0\\x6c\\x9e' | ''' +
                 '''vncviewer localhost:{} PasswordFile=/dev/stdin''').format(port))
        else:
            usage()
    else:
        usage()

if __name__ == "__main__":
    main()
